version: '3'
services:
  mysql:
    image: mysql:8
    restart: always
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=db_aus
    command: mysqld --skip-ssl
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "31000:31000"
    depends_on:
      - mysql