version: '3'
services:
  mysql:
    image: mysql:8
    restart: always
    expose:
      - "3306"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=db_aus
    command: mysqld --skip-ssl
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./logs:/log
    expose:
      - "31000"
    depends_on:
      - mysql
  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    restart: always
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "8080:80"
      - "8000:8000"